# Generated by Django 4.2.6 on 2023-10-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(default='Mounth', max_length=50)),
                ('option1', models.CharField(blank=True, max_length=50)),
                ('option2', models.CharField(blank=True, max_length=50)),
                ('option3', models.CharField(blank=True, max_length=50)),
                ('option4', models.CharField(blank=True, max_length=50)),
                ('option5', models.CharField(blank=True, max_length=50)),
                ('option6', models.CharField(blank=True, max_length=50)),
                ('option7', models.CharField(blank=True, max_length=50)),
                ('option8', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_docs', models.IntegerField()),
                ('number_of_pg', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
    ]
