# Generated by Django 4.2.6 on 2023-10-26 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view', 'Can view specific page'), ('edit', 'Can edit content'), ('comment', 'Can comment'), ('create_new', 'Can create new user')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ManyToManyField(null=True, to='main.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 7, 56, 58, 405724, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
