# Generated by Django 4.2.6 on 2023-10-27 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_option_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(default='customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 9, 44, 15, 169369, tzinfo=datetime.timezone.utc)),
        ),
    ]
