# Generated by Django 4.2.6 on 2023-10-31 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_feature_alter_customuser_joined_userfeaturevote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 9, 16, 55, 811411, tzinfo=datetime.timezone.utc)),
        ),
    ]
