# Generated by Django 4.2.6 on 2023-11-13 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_affiliate_approved_alter_customuser_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 22, 22, 19, 836317, tzinfo=datetime.timezone.utc)),
        ),
    ]
