# Generated by Django 4.2.6 on 2023-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='unique_link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
