# Generated by Django 4.2.6 on 2023-11-02 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chatroom_alter_customuser_joined_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Succes', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='site_code',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='website',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 9, 16, 2, 221573, tzinfo=datetime.timezone.utc)),
        ),
    ]
