# Generated by Django 4.2.6 on 2023-11-08 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_affiliate_customuser_affiliate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.CharField(default='Clear', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 37, 47, 291233, tzinfo=datetime.timezone.utc)),
        ),
    ]
