# Generated by Django 4.2.6 on 2023-11-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='event',
            field=models.CharField(default='affiliate_accept', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='approved',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
