# Generated by Django 4.2.6 on 2023-11-08 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_customer_id_alter_customuser_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 54, 10, 897201, tzinfo=datetime.timezone.utc)),
        ),
    ]
