# Generated by Django 4.2.6 on 2023-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_emailmessage_event_alter_affiliate_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(default='Testing', max_length=255),
            preserve_default=False,
        ),
    ]
