# Generated by Django 4.2.6 on 2023-11-13 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_customuser_affiliate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='affiliate_id',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='affiliated_users',
            field=models.ManyToManyField(related_name='affiliate_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.affiliate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 12, 19, 45, 194504, tzinfo=datetime.timezone.utc)),
        ),
    ]
